	-- =================================================  
	-- PACKAGE: CORE  
	-- COMPONENT : AC_UI_PROPERTY
	-- CREATE : 2018.11.6
	-- UPDATE : 
	-- =================================================	
	CREATE TABLE AC_UI_PROPERTY (
		PROPERTY_NAME	VARCHAR2(100)   NOT NULL,
		PROPERTY_VALUE	VARCHAR2(1024)  NOT NULL,
		CONSTRAINT AC_UI_PROPERTY_PK PRIMARY KEY (PROPERTY_NAME)
	);
	
	CREATE TABLE AC_UI_SEQUENCER(
	SEQUENCER_ID	INTEGER NOT NULL,
	NAME			VARCHAR2(100)   NOT NULL,
	VALUE			INTEGER NOT NULL,
	CONSTRAINT AC_UI_SEQUENCER_PK PRIMARY KEY (SEQUENCER_ID)
	);
	
	CREATE UNIQUE INDEX  "AC_UI_SEQUENCER_UIDX1" ON "AC_UI_SEQUENCER" ("NAME");

	COMMENT ON COLUMN "AC_UI_SEQUENCER"."SEQUENCER_ID" IS '시퀀서 ID';
	COMMENT ON COLUMN "AC_UI_SEQUENCER"."NAME" IS '시퀀서 이름';
	COMMENT ON COLUMN "AC_UI_SEQUENCER"."VALUE" IS '시퀀서 값';
	COMMENT ON TABLE  "AC_UI_SEQUENCER"  IS '애플리케이션 전역에서 사용되는 시퀀서 정보';
	
		-- User
		CREATE TABLE AC_UI_USER (
		  USER_ID                INTEGER NOT NULL,
		  USERNAME               VARCHAR2(100) NOT NULL,
		  PASSWORD_HASH          VARCHAR2(64)  NOT NULL,
		  NAME                   VARCHAR2(100),		  
		  NAME_VISIBLE           NUMBER(1, 0)  DEFAULT 1 ,
		  FIRST_NAME             VARCHAR2(100),		  
		  LAST_NAME              VARCHAR2(100),		
		  EMAIL                  VARCHAR2(100) NOT NULL,
		  EMAIL_VISIBLE          NUMBER(1, 0)  DEFAULT 1,
		  USER_ENABLED           NUMBER(1, 0)  DEFAULT 1, 
		  STATUS                 NUMBER(1, 0)  DEFAULT 0,
		  CREATION_DATE          DATE DEFAULT  SYSDATE NOT NULL,
		  MODIFIED_DATE          DATE DEFAULT  SYSDATE NOT NULL,		    
		  CONSTRAINT AC_UI_USER_PK PRIMARY KEY (USER_ID)
		);		
		
		CREATE UNIQUE INDEX AC_UI_USER_IDX_USERNAME ON AC_UI_USER (USERNAME);
		
		COMMENT ON TABLE  "AC_UI_USER"  IS '사용자 테이블';
		COMMENT ON COLUMN "AC_UI_USER"."USER_ID" IS 'ID'; 
		COMMENT ON COLUMN "AC_UI_USER"."USERNAME" IS '로그인 아이디'; 
        COMMENT ON COLUMN "AC_UI_USER"."NAME" IS '전체 이름';
		COMMENT ON COLUMN "AC_UI_USER"."PASSWORD_HASH" IS '암호화된 패스워드'; 
        COMMENT ON COLUMN "AC_UI_USER"."NAME_VISIBLE" IS '이름 공개 여부';        
		COMMENT ON COLUMN "AC_UI_USER"."FIRST_NAME" IS '이름'; 
        COMMENT ON COLUMN "AC_UI_USER"."LAST_NAME" IS '성';        
		COMMENT ON COLUMN "AC_UI_USER"."EMAIL" IS '메일주소'; 
        COMMENT ON COLUMN "AC_UI_USER"."EMAIL_VISIBLE" IS '메일주소 공개여부';           
		COMMENT ON COLUMN "AC_UI_USER"."USER_ENABLED" IS '계정 사용여부';     
        COMMENT ON COLUMN "AC_UI_USER"."STATUS" IS '계정 상태';	    
        COMMENT ON COLUMN "AC_UI_USER"."CREATION_DATE" IS '생성일자';	    
        COMMENT ON COLUMN "AC_UI_USER"."MODIFIED_DATE" IS '수정일자';	
        
        -- Role
		CREATE TABLE AC_UI_ROLE (
		  ROLE_ID                     INTEGER NOT NULL,
		  NAME                        VARCHAR2(100)   NOT NULL,
		  DESCRIPTION              VARCHAR2(1000)  NOT NULL,
		  CREATION_DATE           DATE DEFAULT  SYSDATE NOT NULL,
		  MODIFIED_DATE           DATE DEFAULT  SYSDATE NOT NULL,	
		  CONSTRAINT AC_UI_ROLE_PK PRIMARY KEY (ROLE_ID)
		);
		
		COMMENT ON TABLE "AC_UI_ROLE"  IS '롤 테이블';
		COMMENT ON COLUMN "AC_UI_ROLE"."ROLE_ID" IS '롤 ID'; 
		COMMENT ON COLUMN "AC_UI_ROLE"."NAME" IS '롤 이름'; 
		COMMENT ON COLUMN "AC_UI_ROLE"."DESCRIPTION" IS '설명'; 	
		COMMENT ON COLUMN "AC_UI_ROLE"."CREATION_DATE" IS '생성일자'; 
		COMMENT ON COLUMN "AC_UI_ROLE"."MODIFIED_DATE" IS '수정일자'; 				
		
		CREATE UNIQUE INDEX AC_UI_ROLE_NAME_IDX ON AC_UI_ROLE (NAME)
		
		-- User Roles  
		CREATE TABLE AC_UI_USER_ROLES (
		  USER_ID                 INTEGER NOT NULL,
		  ROLE_ID                 INTEGER NOT NULL,
		  CONSTRAINT AC_UI_USER_ROLES_PK PRIMARY KEY (USER_ID, ROLE_ID)
		);

		COMMENT ON TABLE "AC_UI_USER_ROLES"  IS '사용자 롤 테이블';
		COMMENT ON COLUMN "AC_UI_USER_ROLES"."USER_ID" IS '그룹 ID'; 
		COMMENT ON COLUMN "AC_UI_USER_ROLES"."ROLE_ID" IS '롤 ID'; 
		
		
		-- User remember me
		CREATE TABLE AC_UI_USER_LOGIN_TOKEN (
			UUID			VARCHAR2(100) NOT NULL,
			USERNAME		VARCHAR2(100) NOT NULL, 
		 	TOKEN 			VARCHAR2(100) NOT NULL, 
		 	LAST_USE_DATE	TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
		);
 
		COMMENT ON TABLE "AC_UI_USER_LOGIN_TOKEN"  IS '인증 정보 저장 테이블';
		COMMENT ON COLUMN "AC_UI_USER_LOGIN_TOKEN"."UUID" IS '시퀀스 값'; 
		COMMENT ON COLUMN "AC_UI_USER_LOGIN_TOKEN"."USERNAME" IS '로그인아이디'; 	
		COMMENT ON COLUMN "AC_UI_USER_LOGIN_TOKEN"."TOKEN" IS '인증 토큰 값'; 
		COMMENT ON COLUMN "AC_UI_USER_LOGIN_TOKEN"."LAST_USE_DATE" IS '마지막 사용일자'; 	
		
	