-- sequencer 

--INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (13,'AVATAR_IMAGE',3);
--INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (21,'SCM',25);
--INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (20,'TASK',37);
--INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (35,'WIKI',27);
INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (1,'USER',2);
INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (2,'GROUP',1);
INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (3,'ROLE',4);
--INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (5,'BOARD',7);
--INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (6,'BOARD_THREAD',42);
--INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (7,'BOARD_MESSAGE',42);
INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (8,'COMMENT',1);
INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (11,'IMAGE',1);
INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (10,'ATTACHMENT',1);
INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (14,'PAGE',2);
INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (15,'PAGE_BODY',2);
--INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (18,'ISSUE',1660);
--INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (19,'PROJECT',34);
--INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (9,'ANNOUNCE',5);
INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (30,'API',1);
INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (4,'CATEGORY',1);
INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (25,'MENU',3);
INSERT INTO AC_UI_SEQUENCER (SEQUENCER_ID,NAME,VALUE) VALUES (26,'MENU_ITEM',12);

-- user 
Insert into AC_UI_USER (USER_ID,USERNAME,PASSWORD_HASH,NAME,NAME_VISIBLE,FIRST_NAME,LAST_NAME,EMAIL,EMAIL_VISIBLE,USER_ENABLED,STATUS ) 
values (1,'king','$2a$10$Ly5hmDajddt0/NtE7PuiLuYLGm85mzcuIOiIogo9QznS7oJae4QWG','킹',0,null,null,'king@king.com',0,1,4 );

Insert into AC_UI_USER_ROLES (USER_ID,ROLE_ID) values (1,1);

-- role 
 

Insert into AC_UI_ROLE (ROLE_ID,NAME,DESCRIPTION ) values (1,'ROLE_ADMINISTRATOR','관리자 롤');
Insert into AC_UI_ROLE (ROLE_ID,NAME,DESCRIPTION ) values (2,'ROLE_DEVELOPER','개발자 롤');
Insert into AC_UI_ROLE (ROLE_ID,NAME,DESCRIPTION ) values (3,'ROLE_USER', '일반 사용자 롤');


-- menu 

INSERT INTO AC_UI_MENU (MENU_ID,NAME,DESCRIPTION) VALUES (1,'USER_TOP_MENU','사용자 TOP 네비게이션 메뉴');
INSERT INTO AC_UI_MENU (MENU_ID,NAME,DESCRIPTION) VALUES (2,'ADMIN_SIDE_MENU','관리자 SIDEMENU');

Insert into AC_UI_MENU_ITEM (MENU_ID,PARENT_ID,MENU_ITEM_ID,SORT_ORDER,NAME,DESCRIPTION,LINK_URL,ROLES,PAGE) values (2,-1,1,1,'설정',null,null,null,null);
Insert into AC_UI_MENU_ITEM (MENU_ID,PARENT_ID,MENU_ITEM_ID,SORT_ORDER,NAME,DESCRIPTION,LINK_URL,ROLES,PAGE) values (2,-1,2,2,'리소스',null,null,null,null);
Insert into AC_UI_MENU_ITEM (MENU_ID,PARENT_ID,MENU_ITEM_ID,SORT_ORDER,NAME,DESCRIPTION,LINK_URL,ROLES,PAGE) values (2,-1,3,3,'보안',null,null,null,null);

Insert into AC_UI_MENU_ITEM (MENU_ID,PARENT_ID,MENU_ITEM_ID,SORT_ORDER,NAME,DESCRIPTION,LINK_URL,ROLES,PAGE) values (2,1,4,1,'시스템 프로퍼티',null,null,null,'manage-properties_v2');

Insert into AC_UI_MENU_ITEM (MENU_ID,PARENT_ID,MENU_ITEM_ID,SORT_ORDER,NAME,DESCRIPTION,LINK_URL,ROLES,PAGE) values (2,2,5,1,'메뉴',null,null,null,'manage-menus');
Insert into AC_UI_MENU_ITEM (MENU_ID,PARENT_ID,MENU_ITEM_ID,SORT_ORDER,NAME,DESCRIPTION,LINK_URL,ROLES,PAGE) values (2,2,6,2,'페이지',null,null,null,'manage-pages');
Insert into AC_UI_MENU_ITEM (MENU_ID,PARENT_ID,MENU_ITEM_ID,SORT_ORDER,NAME,DESCRIPTION,LINK_URL, ROLES,PAGE) values (2,2,7,3,'RESTful API',null,null ,null,'manage-apis_v2');
Insert into AC_UI_MENU_ITEM (MENU_ID,PARENT_ID,MENU_ITEM_ID,SORT_ORDER,NAME,DESCRIPTION,LINK_URL,ROLES,PAGE) values (2,2,8,4,'스크립트',null,null,null,'manage-scripts');
Insert into AC_UI_MENU_ITEM (MENU_ID,PARENT_ID,MENU_ITEM_ID,SORT_ORDER,NAME,DESCRIPTION,LINK_URL, ROLES,PAGE) values (2,2,9,5,'파일',null,null,null,'manage-attachments');
Insert into AC_UI_MENU_ITEM (MENU_ID,PARENT_ID,MENU_ITEM_ID,SORT_ORDER,NAME,DESCRIPTION,LINK_URL, ROLES,PAGE) values (2,2,10,6,'이미지',null,null,null,'manage-images');

Insert into AC_UI_MENU_ITEM (MENU_ID,PARENT_ID,MENU_ITEM_ID,SORT_ORDER,NAME,DESCRIPTION,LINK_URL, ROLES,PAGE) values (2,3,11,1,'사용자',null,null,null,'manage-users');


-- page 
Insert into AC_UI_PAGE (PAGE_ID,OBJECT_TYPE,OBJECT_ID,NAME,VERSION_ID,USER_ID,READ_COUNT) values (1,-1,-1,'index.html',1,1,0);
 
Insert into AC_UI_PAGE_BODY (BODY_ID,PAGE_ID,BODY_TYPE) values (1,1,3);
 
Insert into AC_UI_PAGE_BODY_VERSION (BODY_ID,PAGE_ID,VERSION_ID) values (1,1,1);
 
Insert into AC_UI_PAGE_VERSION (PAGE_ID,VERSION_ID,STATE,TITLE,SECURED,TEMPLATE,SCRIPT,PATTERN,SUMMARY,USER_ID ) values (1,1,'published','DASHBOARD',0,'index.jsp',null,null,null,1 );



