	-- MySQL v5.6.5
	-- =================================================  
	-- PACKAGE: CORE  
	-- COMPONENT : AC_UI_PROPERTY
	-- CREATE : 2018.11.6
	-- UPDATE : 
	-- =================================================	
	CREATE TABLE AC_UI_PROPERTY (
		PROPERTY_NAME	VARCHAR(100)   NOT NULL,
		PROPERTY_VALUE	VARCHAR(1024)  NOT NULL,
		CONSTRAINT AC_UI_PROPERTY_PK PRIMARY KEY (PROPERTY_NAME)
	);
	
	CREATE TABLE AC_UI_SEQUENCER(
	SEQUENCER_ID	INTEGER NOT NULL,
	NAME			VARCHAR(100)   NOT NULL,
	VALUE			INTEGER NOT NULL,
	CONSTRAINT AC_UI_SEQUENCER_PK PRIMARY KEY (SEQUENCER_ID)
	);
	
	CREATE UNIQUE INDEX  `AC_UI_SEQUENCER_UIDX1` ON `AC_UI_SEQUENCER` (`NAME`);

	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_SEQUENCER`.`SEQUENCER_ID` IS '시퀀서 ID'; */
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_SEQUENCER`.`NAME` IS '시퀀서 이름'; */
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_SEQUENCER`.`VALUE` IS '시퀀서 값'; */
	ALTER TABLE  `AC_UI_SEQUENCER`  COMMENT '애플리케이션 전역에서 사용되는 시퀀서 정보';
	
		-- User
		CREATE TABLE AC_UI_USER (
		  USER_ID                INTEGER NOT NULL,
		  USERNAME               VARCHAR(100) NOT NULL,
		  PASSWORD_HASH          VARCHAR(64)  NOT NULL,
		  NAME                   VARCHAR(100),		  
		  NAME_VISIBLE           TINYINT  DEFAULT 1 ,
		  FIRST_NAME             VARCHAR(100),		  
		  LAST_NAME              VARCHAR(100),		
		  EMAIL                  VARCHAR(100) NOT NULL,
		  EMAIL_VISIBLE          TINYINT  DEFAULT 1,
		  USER_ENABLED           TINYINT  DEFAULT 1, 
		  STATUS                 TINYINT  DEFAULT 0,
		  CREATION_DATE          DATETIME DEFAULT  NOW() NOT NULL,
		  MODIFIED_DATE          DATETIME DEFAULT  NOW() NOT NULL,		    
		  CONSTRAINT AC_UI_USER_PK PRIMARY KEY (USER_ID)
		);		
		
		CREATE UNIQUE INDEX AC_UI_USER_IDX_USERNAME ON AC_UI_USER (USERNAME);
		
		ALTER TABLE  `AC_UI_USER`  COMMENT '사용자 테이블';
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER`.`USER_ID` IS 'ID'; */ 
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER`.`USERNAME` IS '로그인 아이디'; */ 
        /* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER`.`NAME` IS '전체 이름'; */
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER`.`PASSWORD_HASH` IS '암호화된 패스워드'; */ 
        /* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER`.`NAME_VISIBLE` IS '이름 공개 여부'; */        
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER`.`FIRST_NAME` IS '이름'; */ 
        /* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER`.`LAST_NAME` IS '성'; */        
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER`.`EMAIL` IS '메일주소'; */ 
        /* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER`.`EMAIL_VISIBLE` IS '메일주소 공개여부'; */           
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER`.`USER_ENABLED` IS '계정 사용여부'; */     
        /* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER`.`STATUS` IS '계정 상태'; */	    
        /* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER`.`CREATION_DATE` IS '생성일자'; */	    
        /* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER`.`MODIFIED_DATE` IS '수정일자'; */	
        
        -- Role
		CREATE TABLE AC_UI_ROLE (
		  ROLE_ID                     INTEGER NOT NULL,
		  NAME                        VARCHAR(100)   NOT NULL,
		  DESCRIPTION              VARCHAR(1000)  NOT NULL,
		  CREATION_DATE           DATETIME DEFAULT  NOW() NOT NULL,
		  MODIFIED_DATE           DATETIME DEFAULT  NOW() NOT NULL,	
		  CONSTRAINT AC_UI_ROLE_PK PRIMARY KEY (ROLE_ID)
		);
		
		ALTER TABLE `AC_UI_ROLE`  COMMENT '롤 테이블';
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_ROLE`.`ROLE_ID` IS '롤 ID'; */ 
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_ROLE`.`NAME` IS '롤 이름'; */ 
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_ROLE`.`DESCRIPTION` IS '설명'; */ 	
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_ROLE`.`CREATION_DATE` IS '생성일자'; */ 
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_ROLE`.`MODIFIED_DATE` IS '수정일자'; */ 				
		
		CREATE UNIQUE INDEX AC_UI_ROLE_NAME_IDX ON AC_UI_ROLE (NAME);
		
		-- User Roles  
		CREATE TABLE AC_UI_USER_ROLES (
		  USER_ID                 INTEGER NOT NULL,
		  ROLE_ID                 INTEGER NOT NULL,
		  CONSTRAINT AC_UI_USER_ROLES_PK PRIMARY KEY (USER_ID, ROLE_ID)
		);

		ALTER TABLE `AC_UI_USER_ROLES`  COMMENT '사용자 롤 테이블';
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER_ROLES`.`USER_ID` IS '그룹 ID'; */ 
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER_ROLES`.`ROLE_ID` IS '롤 ID'; */ 
		
		
		-- User remember me
		CREATE TABLE AC_UI_USER_LOGIN_TOKEN (
			UUID			VARCHAR(100) NOT NULL,
			USERNAME		VARCHAR(100) NOT NULL, 
		 	TOKEN 			VARCHAR(100) NOT NULL, 
		 	LAST_USE_DATE	DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
		);
 
		ALTER TABLE `AC_UI_USER_LOGIN_TOKEN`  COMMENT '인증 정보 저장 테이블';
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER_LOGIN_TOKEN`.`UUID` IS '시퀀스 값'; */ 
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER_LOGIN_TOKEN`.`USERNAME` IS '로그인아이디'; */ 	
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER_LOGIN_TOKEN`.`TOKEN` IS '인증 토큰 값'; */ 
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_USER_LOGIN_TOKEN`.`LAST_USE_DATE` IS '마지막 사용일자'; */ 	
		
	
