	-- MySQL v5.6.5
	-- =================================================  
	-- PACKAGE: IMAGE  
	-- COMPONENT : AVATAR
	-- CREATE : 2018.11.6
	-- UPDATE : 
	-- =================================================	
	
		CREATE TABLE AC_UI_AVATAR_IMAGE (	
			`AVATAR_IMAGE_ID` DECIMAL(38,0) NOT NULL, 
			`USER_ID` DECIMAL(38,0) NOT NULL, 
			`PRIMARY_IMAGE` TINYINT DEFAULT 1, 
			`FILE_NAME` VARCHAR(255) NOT NULL, 
			`FILE_SIZE` DECIMAL(38,0) NOT NULL, 
			`CONTENT_TYPE` VARCHAR(50) NOT NULL, 
			`CREATION_DATE` DATETIME DEFAULT SYSDATE() NOT NULL, 
			`MODIFIED_DATE` DATETIME DEFAULT SYSDATE() NOT NULL, 
			CONSTRAINT AC_UI_AVATAR_IMAGE_PK PRIMARY KEY (AVATAR_IMAGE_ID)
		);
		CREATE INDEX  AC_UI_AVATAR_IMAGE_IDX1  ON AC_UI_AVATAR_IMAGE  (`USER_ID`) ;

		/* Moved to CREATE TABLE
COMMENT ON COLUMN  `AC_UI_AVATAR_IMAGE`.`AVATAR_IMAGE_ID` IS 'ID'; */	 
		/* Moved to CREATE TABLE
COMMENT ON COLUMN  `AC_UI_AVATAR_IMAGE`.`USER_ID` IS '사용자 ID'; */	 
		/* Moved to CREATE TABLE
COMMENT ON COLUMN  `AC_UI_AVATAR_IMAGE`.`PRIMARY_IMAGE` IS '주 이미지 여부'; */	 
		/* Moved to CREATE TABLE
COMMENT ON COLUMN  `AC_UI_AVATAR_IMAGE`.`FILE_NAME` IS '이미지 파일 이름'; */	 
		/* Moved to CREATE TABLE
COMMENT ON COLUMN  `AC_UI_AVATAR_IMAGE`.`FILE_SIZE` IS '이미지 파일 크기'; */	 
	   /* Moved to CREATE TABLE
COMMENT ON COLUMN  `AC_UI_AVATAR_IMAGE`.`CONTENT_TYPE` IS 'CONTENT TYPE 값'; */	 
	   /* Moved to CREATE TABLE
COMMENT ON COLUMN  `AC_UI_AVATAR_IMAGE`.`CREATION_DATE` IS '생성일'; */	 
	   /* Moved to CREATE TABLE
COMMENT ON COLUMN  `AC_UI_AVATAR_IMAGE`.`MODIFIED_DATE` IS '수정일'; */	 
	   ALTER TABLE   `AC_UI_AVATAR_IMAGE`  COMMENT '아바타 이미지 테이블';
 
  		CREATE TABLE  `AC_UI_AVATAR_IMAGE_DATA` (	
  			`AVATAR_IMAGE_ID` DECIMAL(38, 0) NOT NULL COMMENT 'ID', 
			`AVATAR_IMAGE_DATA` LONGBLOB COMMENT '이미지 데이터', 
	 		CONSTRAINT `AC_UI_AVATAR_IMAGE_DATA_PK` PRIMARY KEY (`AVATAR_IMAGE_ID`)
	 	);

		/* Moved to CREATE TABLE
COMMENT ON COLUMN  `AC_UI_AVATAR_IMAGE_DATA`.`AVATAR_IMAGE_ID` IS 'ID'; */ 
		/* Moved to CREATE TABLE
COMMENT ON COLUMN  `AC_UI_AVATAR_IMAGE_DATA`.`AVATAR_IMAGE_DATA` IS '이미지 데이터'; */ 
		ALTER TABLE   `AC_UI_AVATAR_IMAGE_DATA`  COMMENT '아바타 이미지 데이터 테이블'; 	


	-- =================================================  
	--  IMAGE	
	-- =================================================		
		
	CREATE TABLE AC_UI_IMAGE (
		IMAGE_ID                 INTEGER NOT NULL,
		OBJECT_TYPE              INTEGER NOT NULL,
		OBJECT_ID                INTEGER NOT NULL,
		FILE_NAME                VARCHAR(255)   NOT NULL,
		FILE_SIZE                INTEGER   NOT NULL,
		CONTENT_TYPE             VARCHAR(50)  NOT NULL,			  
		USER_ID				   	 INTEGER NOT NULL,	 	
		CREATION_DATE            DATETIME DEFAULT  SYSDATE() NOT NULL,
		MODIFIED_DATE            DATETIME DEFAULT  SYSDATE() NOT NULL,	
		CONSTRAINT AC_UI_IMAGE_PK PRIMARY KEY (IMAGE_ID)
	);		        
		
		
		CREATE INDEX AC_UI_IMAGE_IDX1 ON AC_UI_IMAGE( OBJECT_TYPE, OBJECT_ID ) ;	
		ALTER TABLE `AC_UI_IMAGE`  COMMENT '이미지 테이블';
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_IMAGE`.`IMAGE_ID` IS 'ID'; */ 
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_IMAGE`.`OBJECT_TYPE` IS '이미지와 연관된 모델 유형'; */ 
        /* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_IMAGE`.`OBJECT_ID` IS '이미지와 연관된 모델 ID'; */
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_IMAGE`.`FILE_NAME` IS '이미지 파일 이름'; */ 
        /* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_IMAGE`.`FILE_SIZE` IS '이미지 파일 크기'; */        
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_IMAGE`.`CONTENT_TYPE` IS 'CONTENT TYPE 값'; */ 
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_IMAGE`.`CREATION_DATE` IS '생성일'; */ 
        /* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_IMAGE`.`MODIFIED_DATE` IS '수정일'; */
        
        CREATE TABLE AC_UI_IMAGE_DATA (
			  IMAGE_ID                    INTEGER NOT NULL,
			  IMAGE_DATA               LONGBLOB,
			  CONSTRAINT AC_UI_IMAGE_DATA_PK PRIMARY KEY (IMAGE_ID)
		);		        
		
		ALTER TABLE `AC_UI_IMAGE_DATA`  COMMENT '이미지 데이터 테이블';
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_IMAGE_DATA`.`IMAGE_ID` IS 'ID'; */ 
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_IMAGE_DATA`.`IMAGE_DATA` IS '이미지 데이터'; */ 		
		
				
	-- =================================================  
	--  EXTERNAL_LINK	
	-- =================================================	
		CREATE TABLE AC_UI_EXTERNAL_LINK ( 
			LINK_ID						VARCHAR(255)	NOT NULL, 
			OBJECT_TYPE					INTEGER NOT NULL,		
			OBJECT_ID                INTEGER NOT NULL,
			PUBLIC_SHARED			TINYINT  DEFAULT 1,
			CONSTRAINT AC_UI_LINK_ID_PK PRIMARY KEY (LINK_ID)
		); 		
		
		CREATE UNIQUE INDEX AC_UI_EXTERNAL_LINK_IDX1 ON AC_UI_EXTERNAL_LINK (OBJECT_TYPE, OBJECT_ID);
		
		ALTER TABLE `AC_UI_EXTERNAL_LINK`  COMMENT '외부 링크 테이블';
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_EXTERNAL_LINK`.`LINK_ID` IS '링크 아이디'; */ 
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_EXTERNAL_LINK`.`OBJECT_TYPE` IS '객체타입'; */ 	
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_EXTERNAL_LINK`.`OBJECT_ID` IS '객체 아이디'; */ 	
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_EXTERNAL_LINK`.`PUBLIC_SHARED` IS '공개여부'; */ 	
		
		
	-- =================================================
	-- PACKAGE: UI  
	-- COMPONENT : MENU
	-- CREATE : 2018.11.6
	-- UPDATE : 
	-- =================================================

	CREATE TABLE AC_UI_MENU (
	MENU_ID			INTEGER NOT NULL,
	NAME			VARCHAR(255) NULL,
	DESCRIPTION		VARCHAR(1000),
	CREATION_DATE	DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	MODIFIED_DATE	DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT AC_UI_MENU_PK PRIMARY KEY (MENU_ID)
	);
	
	-- CREATE UNIQUE INDEX AC_UI_MENU_UIDX1 ON AC_UI_MENU (NAME);
	
	ALTER TABLE  `AC_UI_MENU`  COMMENT '메뉴 테이블';
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_MENU`.`MENU_ID` IS '메뉴 ID'; */
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_MENU`.`NAME` IS '메뉴 이름'; */
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_MENU`.`DESCRIPTION` IS '메뉴 설명'; */
	ALTER TABLE `AC_UI_MENU`  COMMENT 'UI 메뉴 테이블';

	CREATE TABLE AC_UI_MENU_PROPERTY (
		  MENU_ID				INTEGER NOT NULL, 
		  PROPERTY_NAME          VARCHAR(100)   NOT NULL,
		  PROPERTY_VALUE         VARCHAR(1024)  NOT NULL,
		  CONSTRAINT AC_UI_MENU_PROPERTY_PK PRIMARY KEY (MENU_ID, PROPERTY_NAME)
	);	

	ALTER TABLE  `AC_UI_MENU_PROPERTY`  COMMENT 'MENU 프로퍼티 테이블';
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_MENU_PROPERTY`.`MENU_ID` IS 'MENU ID'; */  
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_MENU_PROPERTY`.`PROPERTY_NAME` IS '프로퍼티 이름'; */ 
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_MENU_PROPERTY`.`PROPERTY_VALUE` IS '프로퍼티 값'; */  
	
	
	CREATE TABLE AC_UI_MENU_ITEM (
		MENU_ID			INTEGER NOT NULL,
		PARENT_ID		INTEGER NOT NULL,
		MENU_ITEM_ID	INTEGER NOT NULL,
		NAME			VARCHAR(255) NOT NULL,
		SORT_ORDER		INTEGER DEFAULT 1 NULL,
		DESCRIPTION		VARCHAR(4000) NULL,
		LINK_URL		VARCHAR(255) NULL,
		ROLES			VARCHAR(255) NULL,
		PAGE			VARCHAR(255) NULL,	
		CREATION_DATE	DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
		MODIFIED_DATE 	DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
		CONSTRAINT AC_UI_MENU_ITEM_PK PRIMARY KEY (MENU_ITEM_ID)
	);
   
	CREATE INDEX AC_UI_MENU_ITEM_IDX1   ON AC_UI_MENU_ITEM (MENU_ID, PARENT_ID);
   	CREATE INDEX AC_UI_MENU_ITEM_IDX2   ON AC_UI_MENU_ITEM (PARENT_ID);
 
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_MENU_ITEM`.`MENU_ID` IS '메뉴 ID'; */
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_MENU_ITEM`.`PARENT_ID` IS '부모 메뉴 아이템 이름'; */
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_MENU_ITEM`.`MENU_ITEM_ID` IS '메뉴 아이템 ID'; */
	ALTER TABLE `AC_UI_MENU_ITEM`  COMMENT 'UI 메뉴 아이템 테이블';

	CREATE TABLE AC_UI_MENU_ITEM_PROPERTY (
		  MENU_ITEM_ID				INTEGER NOT NULL, 
		  PROPERTY_NAME          VARCHAR(100)   NOT NULL,
		  PROPERTY_VALUE         VARCHAR(1024)  NOT NULL,
		  CONSTRAINT AC_UI_MENU_ITEM_PROPERTY_PK PRIMARY KEY (MENU_ITEM_ID, PROPERTY_NAME)
	);	

	ALTER TABLE  `AC_UI_MENU_ITEM_PROPERTY`  COMMENT 'MENU_ITEM 프로퍼티 테이블'; 
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_MENU_ITEM_PROPERTY`.`MENU_ITEM_ID` IS 'MENU_ITEM ID'; */ 	
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_MENU_ITEM_PROPERTY`.`PROPERTY_NAME` IS '프로퍼티 이름'; */ 
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_MENU_ITEM_PROPERTY`.`PROPERTY_VALUE` IS '프로퍼티 값'; */  
	
	
	-- =================================================  
	-- PACKAGE: UI  
	-- COMPONENT : WIKI
	-- CREATE : 2018.11.6
	-- UPDATE : 
	-- =================================================		
 
	
	CREATE TABLE AC_UI_WIKI(	
		WIKI_ID						INTEGER NOT NULL,
		OBJECT_TYPE					INTEGER NOT NULL,
		OBJECT_ID					INTEGER NOT NULL,
		NAME						VARCHAR(255) NULL,	
		VERSION_ID					INTEGER DEFAULT 1 NOT NULL,
		USER_ID						INTEGER NOT NULL,
		READ_COUNT          		INTEGER DEFAULT 0  NOT NULL,
		CREATION_DATE				DATETIME DEFAULT  SYSDATE() NOT NULL,
		MODIFIED_DATE				DATETIME DEFAULT  SYSDATE() NOT NULL,			
		CONSTRAINT AC_UI_WIKI_PK PRIMARY KEY (WIKI_ID)
	);

	-- CREATE UNIQUE INDEX AC_UI_WIKI_IDX1 ON AC_UI_WIKI (NAME);
	CREATE INDEX AC_UI_WIKI_IDX2   ON AC_UI_WIKI (OBJECT_TYPE, OBJECT_ID, WIKI_ID);
	CREATE INDEX AC_UI_WIKI_IDX3   ON AC_UI_WIKI (USER_ID);

	CREATE TABLE AC_UI_WIKI_BODY
	(	
		BODY_ID						INTEGER NOT NULL,
		WIKI_ID						INTEGER NOT NULL, 
		BODY_TEXT					LONGTEXT,
		CONSTRAINT AC_UI_WIKI_BODY_PK PRIMARY KEY (BODY_ID)
    ) ;
	
		
	CREATE TABLE AC_UI_WIKI_BODY_VERSION
	(	
		BODY_ID					INTEGER NOT NULL,
		WIKI_ID					INTEGER NOT NULL,
		VERSION_ID				INTEGER DEFAULT 1 NOT NULL ,
		CONSTRAINT AC_UI_WIKI_BODY_VERSION_PK PRIMARY KEY (BODY_ID, WIKI_ID, VERSION_ID )
   );
   
   CREATE INDEX AC_UI_WIKI_BODY_VERSION_IDX1   ON AC_UI_WIKI_BODY_VERSION (WIKI_ID, VERSION_ID);

		
  CREATE TABLE AC_UI_WIKI_VERSION
   (	
	WIKI_ID					INTEGER NOT NULL,
	VERSION_ID				INTEGER DEFAULT 1 NOT NULL ,
	STATE					VARCHAR(20), 
	TITLE					VARCHAR(255), 
	SECURED          		TINYINT  DEFAULT 1,
	USER_ID					INTEGER	NOT NULL,
	CREATION_DATE			DATETIME DEFAULT  SYSDATE() NOT NULL,
	MODIFIED_DATE			DATETIME DEFAULT  SYSDATE() NOT NULL,	
	CONSTRAINT AC_UI_WIKI_VERSION_PK PRIMARY KEY (WIKI_ID, VERSION_ID)
   ) ;

		
	CREATE INDEX AC_UI_WIKI_VERSION_IDX1   ON AC_UI_WIKI_VERSION (CREATION_DATE);
	CREATE INDEX AC_UI_WIKI_VERSION_IDX2   ON AC_UI_WIKI_VERSION (MODIFIED_DATE);
	CREATE INDEX AC_UI_WIKI_VERSION_IDX3   ON AC_UI_WIKI_VERSION (TITLE);
	CREATE INDEX AC_UI_WIKI_VERSION_IDX4   ON AC_UI_WIKI_VERSION (WIKI_ID, STATE);

			
	CREATE TABLE AC_UI_WIKI_PROPERTY (
		  WIKI_ID				INTEGER NOT NULL,
		  VERSION_ID			INTEGER DEFAULT 1 NOT NULL,
		  PROPERTY_NAME          VARCHAR(100)   NOT NULL,
		  PROPERTY_VALUE         VARCHAR(1024)  NOT NULL,
		  CONSTRAINT AC_UI_WIKI_PROPERTY_PK PRIMARY KEY (WIKI_ID, VERSION_ID, PROPERTY_NAME)
	);	

	ALTER TABLE  `AC_UI_WIKI_PROPERTY`  COMMENT 'WIKI 프로퍼티 테이블';
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_WIKI_PROPERTY`.`WIKI_ID` IS 'WIKI ID'; */ 
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_WIKI_PROPERTY`.`VERSION_ID` IS 'WIKI VERSION'; */ 	
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_WIKI_PROPERTY`.`PROPERTY_NAME` IS '프로퍼티 이름'; */ 
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_WIKI_PROPERTY`.`PROPERTY_VALUE` IS '프로퍼티 값'; */  
	
	-- =================================================  
	-- PACKAGE: UI  
	-- COMPONENT : SCRIPT OR TEMPLETE SOURCE  
	-- CREATE : 2018.10.18
	-- UPDATE : 
	-- =================================================		
		
	CREATE TABLE AC_UI_SCRIPT_SOURCE
		SOURCE_ID					INTEGER NOT NULL,
		OBJECT_TYPE					INTEGER NOT NULL,
		OBJECT_ID					INTEGER NOT NULL,		
		SOURCE_TYPE					INTEGER NOT NULL,
		SOURCE_TEXT					CLOB,
		CREATION_DATE				DATE DEFAULT  SYSDATE() NOT NULL,
		MODIFIED_DATE				DATE DEFAULT  SYSDATE() NOT NULL,
		CONSTRAINT AC_UI_SCRIPT_SOURCE_PK PRIMARY KEY (SOURCE_ID)
	);
	
	-- =================================================  
	-- PACKAGE: UI  
	-- COMPONENT : API 
	-- CREATE : 2018.10.18
	-- UPDATE : 
	-- =================================================		
	CREATE TABLE AC_UI_API (
		OBJECT_TYPE				INTEGER NOT NULL,
		OBJECT_ID				INTEGER NOT NULL,	
		
		API_ID					INTEGER NOT NULL,
		TITLE				VARCHAR(255), 
		API_NAME				VARCHAR(255) NOT NULL,
		API_VERSION				VARCHAR(255) NOT NULL,
		DESCRIPTION				VARCHAR(1000),
		
		CONTENT_TYPE			VARCHAR(50), 
		SECURED					TINYINT  DEFAULT 1,
		ENABLED					DOUBLE DEFAULT 0,	
		SCRIPT					VARCHAR(255), 
		PATTERN					VARCHAR(255), 
		CREATOR_ID				INTEGER NOT NULL,
		CREATION_DATE			DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
		MODIFIED_DATE			DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
		CONSTRAINT AC_UI_API_PK PRIMARY KEY (API_ID)
	);	
	
	CREATE INDEX AC_UI_API_IDX_01 ON AC_UI_API (OBJECT_TYPE, OBJECT_ID);

	CREATE TABLE `AC_UI_API_PROPERTY` (	
	`API_ID` DECIMAL(38,0) NOT NULL COMMENT 'TASK ID', 
	`PROPERTY_NAME` VARCHAR(100) NOT NULL COMMENT '프로퍼티 이름', 
	`PROPERTY_VALUE` VARCHAR(1024) NOT NULL COMMENT '프로퍼티 값', 
	CONSTRAINT `AC_UI_API_PROPERTY_PK` PRIMARY KEY (`API_ID`, `PROPERTY_NAME`));

	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_API_PROPERTY`.`API_ID` IS 'TASK ID'; */ 
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_API_PROPERTY`.`PROPERTY_NAME` IS '프로퍼티 이름'; */ 
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_API_PROPERTY`.`PROPERTY_VALUE` IS '프로퍼티 값'; */ 
	ALTER TABLE  `AC_UI_API_PROPERTY`  COMMENT 'TASK 프로퍼티 테이블';	
	
	-- =================================================  
	-- PACKAGE: UI  
	-- COMPONENT : PAGE 
	-- CREATE : 2018.09.19
	-- UPDATE :
	-- 2018.09.17 - AC_UI_PAGE_BODY_VERSION.SCRIPT 추가 
	-- =================================================	
	CREATE TABLE AC_UI_PAGE(	
		PAGE_ID						INTEGER NOT NULL,
		OBJECT_TYPE					INTEGER NOT NULL,
		OBJECT_ID					INTEGER NOT NULL,
		NAME						VARCHAR(255) NOT NULL,	
		VERSION_ID					INTEGER DEFAULT 1 NOT NULL,
		USER_ID						INTEGER NOT NULL,
		READ_COUNT          		INTEGER DEFAULT 0  NOT NULL,
		PATTERN						VARCHAR(255) NULL,	
		CREATION_DATE				DATETIME DEFAULT  SYSDATE() NOT NULL,
		MODIFIED_DATE				DATETIME DEFAULT  SYSDATE() NOT NULL,			
		CONSTRAINT AC_UI_PAGE_PK PRIMARY KEY (PAGE_ID)
	);

	CREATE UNIQUE INDEX AC_UI_PAGE_IDX1 ON REP_PAGE (NAME);
	CREATE INDEX AC_UI_PAGE_IDX2   ON REP_PAGE (OBJECT_TYPE, OBJECT_ID, PAGE_ID);
	CREATE INDEX AC_UI_PAGE_IDX3   ON REP_PAGE (USER_ID);

	CREATE TABLE AC_UI_PAGE_BODY
	(	
		BODY_ID						INTEGER NOT NULL,
		PAGE_ID						INTEGER NOT NULL,
		BODY_TYPE					INTEGER NOT NULL,
		BODY_TEXT					LONGTEXT,
		CONSTRAINT AC_UI_PAGE_BODY_PK PRIMARY KEY (BODY_ID)
    ) ;
	
		
	CREATE TABLE AC_UI_PAGE_BODY_VERSION
	(	
		BODY_ID					INTEGER NOT NULL,
		PAGE_ID						INTEGER NOT NULL,
		VERSION_ID				INTEGER DEFAULT 1 NOT NULL ,
		CONSTRAINT AC_UI_PAGE_BODY_VERSION_PK PRIMARY KEY (BODY_ID, PAGE_ID, VERSION_ID )
   );
   
   CREATE INDEX AC_UI_PAGE_BODY_VERSION_IDX1   ON AC_UI_PAGE_BODY_VERSION (PAGE_ID, VERSION_ID);

		
  CREATE TABLE AC_UI_PAGE_VERSION
   (	
	PAGE_ID					INTEGER NOT NULL,
	VERSION_ID				INTEGER DEFAULT 1 NOT NULL ,
	STATE					VARCHAR(20), 
	TITLE					VARCHAR(255), 
	SECURED          		TINYINT  DEFAULT 1,
	TEMPLATE				VARCHAR(255), 
	SCRIPT					VARCHAR(255), 
	PATTERN					VARCHAR(255), 	
	SUMMARY					VARCHAR(4000), 
	USER_ID					INTEGER	NOT NULL,
	CREATION_DATE			DATETIME DEFAULT  SYSDATE() NOT NULL,
	MODIFIED_DATE			DATETIME DEFAULT  SYSDATE() NOT NULL,	
	CONSTRAINT AC_UI_PAGE_VERSION_PK PRIMARY KEY (PAGE_ID, VERSION_ID)
   ) ;

		
	CREATE INDEX AC_UI_PAGE_VERSION_IDX1   ON AC_UI_PAGE_VERSION (CREATION_DATE);
	CREATE INDEX AC_UI_PAGE_VERSION_IDX2   ON AC_UI_PAGE_VERSION (MODIFIED_DATE);
	CREATE INDEX AC_UI_PAGE_VERSION_IDX3   ON AC_UI_PAGE_VERSION (TITLE);
	CREATE INDEX AC_UI_PAGE_VERSION_IDX4   ON AC_UI_PAGE_VERSION (PAGE_ID, STATE);

			
	CREATE TABLE AC_UI_PAGE_PROPERTY (
		  PAGE_ID				INTEGER NOT NULL,
		  VERSION_ID				INTEGER DEFAULT 1 NOT NULL,
		  PROPERTY_NAME          VARCHAR(100)   NOT NULL,
		  PROPERTY_VALUE         VARCHAR(1024)  NOT NULL,
		  CONSTRAINT AC_UI_PAGE_PROPERTY_PK PRIMARY KEY (PAGE_ID, VERSION_ID, PROPERTY_NAME)
	);	

	ALTER TABLE  `AC_UI_PAGE_PROPERTY`  COMMENT 'PAGE 프로퍼티 테이블';
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_PAGE_PROPERTY`.`PAGE_ID` IS 'PAGE ID'; */ 
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_PAGE_PROPERTY`.`VERSION_ID` IS 'PAGE VERSION'; */ 	
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_PAGE_PROPERTY`.`PROPERTY_NAME` IS '프로퍼티 이름'; */ 
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_PAGE_PROPERTY`.`PROPERTY_VALUE` IS '프로퍼티 값'; */ 	 

	-- =================================================  
	--  VIEWCOUNT	
	-- =================================================	
		CREATE TABLE AC_UI_VIEWCOUNT(	
			ENTITY_TYPE					INTEGER NOT NULL,
			ENTITY_ID					INTEGER NOT NULL,
			VIEWCOUNT					INTEGER NOT NULL,
			CONSTRAINT AC_UI_VIEWCOUNT_PK PRIMARY KEY (ENTITY_TYPE, ENTITY_ID)
   		);		
   		
   		ALTER TABLE `AC_UI_VIEWCOUNT`  COMMENT '뷰 카운트 테이블';
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_VIEWCOUNT`.`ENTITY_TYPE` IS '객체 타입'; */ 
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_VIEWCOUNT`.`ENTITY_ID` IS '객체 아이디'; */ 
		/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_VIEWCOUNT`.`VIEWCOUNT` IS '카운트'; */ 

		
	-- =================================================  
	--  TAG	
	-- =================================================	
	
    CREATE TABLE AC_UI_TAG(	 
	    TAG_ID					INTEGER NOT NULL,	
	    TAG_NAME				VARCHAR(100) NOT NULL,
	    CREATION_DATE		DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
	    CONSTRAINT AC_UI_TAG_PK PRIMARY KEY (TAG_ID)
    );
   
    CREATE UNIQUE INDEX AC_UI_TAG_IDX1 ON AC_UI_TAG( TAG_NAME ) ;	
    CREATE INDEX AC_UI_TAG_IDX2 ON AC_UI_TAG (CREATION_DATE) ;
   
    CREATE TABLE AC_UI_OBJECT_TAG(	 
    		TAG_ID					INTEGER NOT NULL,	
		OBJECT_TYPE			INTEGER NOT NULL,
		OBJECT_ID				INTEGER NOT NULL,
   		CREATION_DATE		DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL
	);
    
	CREATE INDEX AC_UI_OBJECT_TAG_IDX1 ON AC_UI_OBJECT_TAG (OBJECT_ID, TAG_ID, OBJECT_TYPE) ;
    CREATE INDEX AC_UI_OBJECT_TAG_IDX2 ON AC_UI_OBJECT_TAG (TAG_ID) ;
    CREATE INDEX AC_UI_OBJECT_TAG_IDX3 ON AC_UI_OBJECT_TAG (OBJECT_TYPE, OBJECT_ID, CREATION_DATE, TAG_ID) ;
    CREATE INDEX AC_UI_OBJECT_TAG_IDX4 ON AC_UI_OBJECT_TAG (OBJECT_TYPE, TAG_ID) ;

	
	-- =================================================  
	--  COMMENT	
	-- =================================================	
	CREATE TABLE AC_UI_COMMENT(	
		COMMENT_ID					INTEGER NOT NULL,		
		OBJECT_TYPE					INTEGER NOT NULL,
		OBJECT_ID						INTEGER NOT NULL,
		PARENT_COMMENT_ID		INTEGER,
		PARENT_OBJECT_TYPE		INTEGER,
		PARENT_OBJECT_ID			INTEGER,
		USER_ID						INTEGER,
		NAME							VARCHAR(100),
		EMAIL							VARCHAR(255),
		URL								VARCHAR(255),
		IP								VARCHAR(15),
		BODY                            VARCHAR(4000),
		STATUS							INTEGER NOT NULL, 
		CREATION_DATE				DATETIME DEFAULT  SYSDATE() NOT NULL,
		MODIFIED_DATE				DATETIME DEFAULT  SYSDATE() NOT NULL,		
		CONSTRAINT AC_UI_COMMENT_PK PRIMARY KEY (COMMENT_ID)
   );	
   
	CREATE INDEX AC_UI_COMMENT_IDX1 ON AC_UI_COMMENT (CREATION_DATE) ;
	CREATE INDEX AC_UI_COMMENT_IDX2 ON AC_UI_COMMENT (MODIFIED_DATE) ;
	CREATE INDEX AC_UI_COMMENT_IDX3 ON AC_UI_COMMENT (OBJECT_TYPE, OBJECT_ID) ;
	CREATE INDEX AC_UI_COMMENT_IDX4 ON AC_UI_COMMENT (PARENT_OBJECT_TYPE, PARENT_OBJECT_ID) ;
	CREATE INDEX AC_UI_COMMENT_IDX5 ON AC_UI_COMMENT (USER_ID) ;
	
	CREATE TABLE AC_UI_COMMENT_PROPERTY (
	  COMMENT_ID               INTEGER NOT NULL,
	  PROPERTY_NAME          VARCHAR(100)   NOT NULL,
	  PROPERTY_VALUE         VARCHAR(1024)  NOT NULL,
	  CONSTRAINT AC_UI_COMMENT_PROPERTY_PK PRIMARY KEY (COMMENT_ID, PROPERTY_NAME)
	);	
	
	ALTER TABLE      `AC_UI_COMMENT_PROPERTY`  COMMENT 'COMMENT 프로퍼티 테이블';
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_COMMENT_PROPERTY_PK`.`COMMENT_ID` IS 'COMMENT ID'; */ 
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_COMMENT_PROPERTY_PK`.`PROPERTY_NAME` IS '프로퍼티 이름'; */ 
	/* Moved to CREATE TABLE
COMMENT ON COLUMN `AC_UI_COMMENT_PROPERTY_PK`.`PROPERTY_VALUE` IS '프로퍼티 값'; */ 		
	
	    
    
	-- =================================================  
	--  UI CONTACTS	
	-- =================================================	
	CREATE TABLE AC_UI_CONTACT (
		CONTACT_ID				INTEGER NOT NULL,
		COMPANY_NAME			VARCHAR(255) NOT NULL,
		JOB_TITLE				VARCHAR(500) NOT NULL,
		NAME					VARCHAR(255) NOT NULL,
		EMAIL					VARCHAR(255) NOT NULL,
		TELEPHONE				VARCHAR(255) NOT NULL,
		MOBILEPHONE				VARCHAR(255) NOT NULL,
		NOTE					VARCHAR(4000),
		CREATION_DATE			DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
		MODIFIED_DATE			DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
		CONSTRAINT AC_UI_CONTACT_PK PRIMARY KEY (CONTACT_ID)
	);	
	
	
	CREATE TABLE AC_UI_CALENDAR (
		CALENDAR_ID				INTEGER NOT NULL,
		CALENDAR_NAME			VARCHAR(255) NOT NULL,
		TIMEZONE				VARCHAR(500) NOT NULL,
		DESCRIPTION				VARCHAR(4000),
		USER_ID					INTEGER NOT NULL,
		CREATION_DATE			DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
		MODIFIED_DATE			DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
		CONSTRAINT AC_UI_CALENDAR_PK PRIMARY KEY (CALENDAR_ID)
	);	
		
